### PR TITLE
Add Docker and Docker Compose support

### PR DESCRIPTION
**Pull request by leozz37**
Implemented Docker support, to run the application inside a container.

Instructions on how to run them is on the `README.md`.

 Add `Dockerfile` and `docker-compose.yml` files.

### CODE REVIEW

**Comment by alvarowolfx** [comment]
Hey @leozz37, sorry for the late response and thanks for the PR.

I think we can simplify and reduce the size of the Docker image by using multi-stage builds and a distroless image.

Here's an example for doing so:
https://github.com/alvarowolfx/gcloud-dota-app/blob/master/go-api/Dockerfile

**Comment by leozz37** [comment]
Awesome, I'll do it!

**Comment by leozz37** [comment]
@alvarowolfx done!

**Comment by alvarowolfx** [comment]
Awesome, thanks for the improvements.

**Pull request merged**
